### ISSUE TITLE
Should JSON PATH be part of the ASDF deliverables?

### ISSUE THREAD

**Issue by mcr** [one-data-model/ietf108#5]
In the process, some smaller pieces may become usable independently from
    SDF itself and its applications. JSON Path (similar to, but different in
     scope from JSON Pointer documented in RFC6901) might be an example for
     such a spin-off specification -- it is currently defined on a website
     and would benefit from a more formal definition so it can be used in
     discovery processes involving SDF models.

The web site in question is, I think: https://jsonpath.com/ ?
             https://goessner.net/articles/JsonPath/
             https://restfulapi.net/json-jsonpath/  <- seems most authoritative

Is it a goal to do this work in ASDF?

**Comment by cabo** [comment]
We won't have to -- please see discussion in

Archived-At: <https://mailarchive.ietf.org/arch/msg/asdf/qJ8CkCHmso-SLnyT_t1bsFw3eUU>
Archived-At: <https://mailarchive.ietf.org/arch/msg/asdf/nI5w94AuHqeEz-ILb8xarnzR7pM>

Also, it now seems JSONPath will be more interesting for *users* of SDF (e.g., in discovery) than as a normative reference of SDF itself.  But that is hard to predict.

Please close if you think your question has been answered.
